apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cheese
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      taskSpec:
        steps:
        - image: uses:./test_data/load_pipelinerun/pipeline-finally-uses/common.yaml
          name: common-build
    finally:
    - name: from-build-pack-finally
      taskSpec:
        steps:
        - image: uses:./test_data/load_pipelinerun/pipeline-finally-uses/common.yaml
          name: common-build
          env:
          - name: FOO
            value: finally
