{{- if .Values.strobe.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "strobe.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lighthouse.jenkins.io
  resources:
  - lighthousejobs
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - lighthouse.jenkins.io
  resources:
  - lighthousejobs/status
  verbs:
  - update
{{- end }}
