{{- if .Values.githubApp.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tide-githubapp-tokens
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  username: {{ default "jenkins-x[bot]" .Values.githubApp.username | b64enc | quote }}
{{- end }}
